export interface CountryPhone {
  countryname: string;
  flag: string;
  code: string;
  iso: string;
}

const COUNTRY_PHONES: CountryPhone[] = [
  { countryname: "Afghanistan", flag: "🇦🇫", code: "+93", iso: "AF" },
  { countryname: "Albania", flag: "🇦🇱", code: "+355", iso: "AL" },
  { countryname: "Algeria", flag: "🇩🇿", code: "+213", iso: "DZ" },
  { countryname: "Andorra", flag: "🇦🇩", code: "+376", iso: "AD" },
  { countryname: "Angola", flag: "🇦🇴", code: "+244", iso: "AO" },
  { countryname: "Argentina", flag: "🇦🇷", code: "+54", iso: "AR" },
  { countryname: "Armenia", flag: "🇦🇲", code: "+374", iso: "AM" },
  { countryname: "Australia", flag: "🇦🇺", code: "+61", iso: "AU" },
  { countryname: "Austria", flag: "🇦🇹", code: "+43", iso: "AT" },
  { countryname: "Azerbaijan", flag: "🇦🇿", code: "+994", iso: "AZ" },
  { countryname: "Bahamas", flag: "🇧🇸", code: "+1242", iso: "BS" },
  { countryname: "Bahrain", flag: "🇧🇭", code: "+973", iso: "BH" },
  { countryname: "Bangladesh", flag: "🇧🇩", code: "+880", iso: "BD" },
  { countryname: "Barbados", flag: "🇧🇧", code: "+1246", iso: "BB" },
  { countryname: "Belarus", flag: "🇧🇾", code: "+375", iso: "BY" },
  { countryname: "Belgium", flag: "🇧🇪", code: "+32", iso: "BE" },
  { countryname: "Belize", flag: "🇧🇿", code: "+501", iso: "BZ" },
  { countryname: "Benin", flag: "🇧🇯", code: "+229", iso: "BJ" },
  { countryname: "Bhutan", flag: "🇧🇹", code: "+975", iso: "BT" },
  { countryname: "Bolivia", flag: "🇧🇴", code: "+591", iso: "BO" },
  { countryname: "Bosnia and Herzegovina", flag: "🇧🇦", code: "+387", iso: "BA" },
  { countryname: "Botswana", flag: "🇧🇼", code: "+267", iso: "BW" },
  { countryname: "Brazil", flag: "🇧🇷", code: "+55", iso: "BR" },
  { countryname: "Brunei", flag: "🇧🇳", code: "+673", iso: "BN" },
  { countryname: "Bulgaria", flag: "🇧🇬", code: "+359", iso: "BG" },
  { countryname: "Burkina Faso", flag: "🇧🇫", code: "+226", iso: "BF" },
  { countryname: "Burundi", flag: "🇧🇮", code: "+257", iso: "BI" },
  { countryname: "Cambodia", flag: "🇰🇭", code: "+855", iso: "KH" },
  { countryname: "Cameroon", flag: "🇨🇲", code: "+237", iso: "CM" },
  { countryname: "Canada", flag: "🇨🇦", code: "+1", iso: "CA" },
  { countryname: "Cape Verde", flag: "🇨🇻", code: "+238", iso: "CV" },
  { countryname: "Central African Republic", flag: "🇨🇫", code: "+236", iso: "CF" },
  { countryname: "Chad", flag: "🇹🇩", code: "+235", iso: "TD" },
  { countryname: "Chile", flag: "🇨🇱", code: "+56", iso: "CL" },
  { countryname: "China", flag: "🇨🇳", code: "+86", iso: "CN" },
  { countryname: "Colombia", flag: "🇨🇴", code: "+57", iso: "CO" },
  { countryname: "Comoros", flag: "🇰🇲", code: "+269", iso: "KM" },
  { countryname: "Congo (DRC)", flag: "🇨🇩", code: "+243", iso: "CD" },
  { countryname: "Congo (Republic)", flag: "🇨🇬", code: "+242", iso: "CG" },
  { countryname: "Costa Rica", flag: "🇨🇷", code: "+506", iso: "CR" },
  { countryname: "Croatia", flag: "🇭🇷", code: "+385", iso: "HR" },
  { countryname: "Cuba", flag: "🇨🇺", code: "+53", iso: "CU" },
  { countryname: "Cyprus", flag: "🇨🇾", code: "+357", iso: "CY" },
  { countryname: "Czech Republic", flag: "🇨🇿", code: "+420", iso: "CZ" },
  { countryname: "Denmark", flag: "🇩🇰", code: "+45", iso: "DK" },
  { countryname: "Djibouti", flag: "🇩🇯", code: "+253", iso: "DJ" },
  { countryname: "Dominican Republic", flag: "🇩🇴", code: "+1809", iso: "DO" },
  { countryname: "Ecuador", flag: "🇪🇨", code: "+593", iso: "EC" },
  { countryname: "Egypt", flag: "🇪🇬", code: "+20", iso: "EG" },
  { countryname: "El Salvador", flag: "🇸🇻", code: "+503", iso: "SV" },
  { countryname: "Equatorial Guinea", flag: "🇬🇶", code: "+240", iso: "GQ" },
  { countryname: "Eritrea", flag: "🇪🇷", code: "+291", iso: "ER" },
  { countryname: "Estonia", flag: "🇪🇪", code: "+372", iso: "EE" },
  { countryname: "Eswatini", flag: "🇸🇿", code: "+268", iso: "SZ" },
  { countryname: "Ethiopia", flag: "🇪🇹", code: "+251", iso: "ET" },
  { countryname: "Fiji", flag: "🇫🇯", code: "+679", iso: "FJ" },
  { countryname: "Finland", flag: "🇫🇮", code: "+358", iso: "FI" },
  { countryname: "France", flag: "🇫🇷", code: "+33", iso: "FR" },
  { countryname: "Gabon", flag: "🇬🇦", code: "+241", iso: "GA" },
  { countryname: "Gambia", flag: "🇬🇲", code: "+220", iso: "GM" },
  { countryname: "Georgia", flag: "🇬🇪", code: "+995", iso: "GE" },
  { countryname: "Germany", flag: "🇩🇪", code: "+49", iso: "DE" },
  { countryname: "Ghana", flag: "🇬🇭", code: "+233", iso: "GH" },
  { countryname: "Greece", flag: "🇬🇷", code: "+30", iso: "GR" },
  { countryname: "Guatemala", flag: "🇬🇹", code: "+502", iso: "GT" },
  { countryname: "Guinea", flag: "🇬🇳", code: "+224", iso: "GN" },
  { countryname: "Guinea-Bissau", flag: "🇬🇼", code: "+245", iso: "GW" },
  { countryname: "Guyana", flag: "🇬🇾", code: "+592", iso: "GY" },
  { countryname: "Haiti", flag: "🇭🇹", code: "+509", iso: "HT" },
  { countryname: "Honduras", flag: "🇭🇳", code: "+504", iso: "HN" },
  { countryname: "Hong Kong", flag: "🇭🇰", code: "+852", iso: "HK" },
  { countryname: "Hungary", flag: "🇭🇺", code: "+36", iso: "HU" },
  { countryname: "Iceland", flag: "🇮🇸", code: "+354", iso: "IS" },
  { countryname: "India", flag: "🇮🇳", code: "+91", iso: "IN" },
  { countryname: "Indonesia", flag: "🇮🇩", code: "+62", iso: "ID" },
  { countryname: "Iran", flag: "🇮🇷", code: "+98", iso: "IR" },
  { countryname: "Iraq", flag: "🇮🇶", code: "+964", iso: "IQ" },
  { countryname: "Ireland", flag: "🇮🇪", code: "+353", iso: "IE" },
  { countryname: "Israel", flag: "🇮🇱", code: "+972", iso: "IL" },
  { countryname: "Italy", flag: "🇮🇹", code: "+39", iso: "IT" },
  { countryname: "Ivory Coast", flag: "🇨🇮", code: "+225", iso: "CI" },
  { countryname: "Jamaica", flag: "🇯🇲", code: "+1876", iso: "JM" },
  { countryname: "Japan", flag: "🇯🇵", code: "+81", iso: "JP" },
  { countryname: "Jordan", flag: "🇯🇴", code: "+962", iso: "JO" },
  { countryname: "Kazakhstan", flag: "🇰🇿", code: "+7", iso: "KZ" },
  { countryname: "Kenya", flag: "🇰🇪", code: "+254", iso: "KE" },
  { countryname: "Kuwait", flag: "🇰🇼", code: "+965", iso: "KW" },
  { countryname: "Kyrgyzstan", flag: "🇰🇬", code: "+996", iso: "KG" },
  { countryname: "Laos", flag: "🇱🇦", code: "+856", iso: "LA" },
  { countryname: "Latvia", flag: "🇱🇻", code: "+371", iso: "LV" },
  { countryname: "Lebanon", flag: "🇱🇧", code: "+961", iso: "LB" },
  { countryname: "Lesotho", flag: "🇱🇸", code: "+266", iso: "LS" },
  { countryname: "Liberia", flag: "🇱🇷", code: "+231", iso: "LR" },
  { countryname: "Libya", flag: "🇱🇾", code: "+218", iso: "LY" },
  { countryname: "Liechtenstein", flag: "🇱🇮", code: "+423", iso: "LI" },
  { countryname: "Lithuania", flag: "🇱🇹", code: "+370", iso: "LT" },
  { countryname: "Luxembourg", flag: "🇱🇺", code: "+352", iso: "LU" },
  { countryname: "Madagascar", flag: "🇲🇬", code: "+261", iso: "MG" },
  { countryname: "Malawi", flag: "🇲🇼", code: "+265", iso: "MW" },
  { countryname: "Malaysia", flag: "🇲🇾", code: "+60", iso: "MY" },
  { countryname: "Maldives", flag: "🇲🇻", code: "+960", iso: "MV" },
  { countryname: "Mali", flag: "🇲🇱", code: "+223", iso: "ML" },
  { countryname: "Malta", flag: "🇲🇹", code: "+356", iso: "MT" },
  { countryname: "Mauritania", flag: "🇲🇷", code: "+222", iso: "MR" },
  { countryname: "Mauritius", flag: "🇲🇺", code: "+230", iso: "MU" },
  { countryname: "Mexico", flag: "🇲🇽", code: "+52", iso: "MX" },
  { countryname: "Moldova", flag: "🇲🇩", code: "+373", iso: "MD" },
  { countryname: "Monaco", flag: "🇲🇨", code: "+377", iso: "MC" },
  { countryname: "Mongolia", flag: "🇲🇳", code: "+976", iso: "MN" },
  { countryname: "Montenegro", flag: "🇲🇪", code: "+382", iso: "ME" },
  { countryname: "Morocco", flag: "🇲🇦", code: "+212", iso: "MA" },
  { countryname: "Mozambique", flag: "🇲🇿", code: "+258", iso: "MZ" },
  { countryname: "Myanmar", flag: "🇲🇲", code: "+95", iso: "MM" },
  { countryname: "Namibia", flag: "🇳🇦", code: "+264", iso: "NA" },
  { countryname: "Nepal", flag: "🇳🇵", code: "+977", iso: "NP" },
  { countryname: "Netherlands", flag: "🇳🇱", code: "+31", iso: "NL" },
  { countryname: "New Zealand", flag: "🇳🇿", code: "+64", iso: "NZ" },
  { countryname: "Nicaragua", flag: "🇳🇮", code: "+505", iso: "NI" },
  { countryname: "Niger", flag: "🇳🇪", code: "+227", iso: "NE" },
  { countryname: "Nigeria", flag: "🇳🇬", code: "+234", iso: "NG" },
  { countryname: "North Macedonia", flag: "🇲🇰", code: "+389", iso: "MK" },
  { countryname: "Norway", flag: "🇳🇴", code: "+47", iso: "NO" },
  { countryname: "Oman", flag: "🇴🇲", code: "+968", iso: "OM" },
  { countryname: "Pakistan", flag: "🇵🇰", code: "+92", iso: "PK" },
  { countryname: "Palestine", flag: "🇵🇸", code: "+970", iso: "PS" },
  { countryname: "Panama", flag: "🇵🇦", code: "+507", iso: "PA" },
  { countryname: "Papua New Guinea", flag: "🇵🇬", code: "+675", iso: "PG" },
  { countryname: "Paraguay", flag: "🇵🇾", code: "+595", iso: "PY" },
  { countryname: "Peru", flag: "🇵🇪", code: "+51", iso: "PE" },
  { countryname: "Philippines", flag: "🇵🇭", code: "+63", iso: "PH" },
  { countryname: "Poland", flag: "🇵🇱", code: "+48", iso: "PL" },
  { countryname: "Portugal", flag: "🇵🇹", code: "+351", iso: "PT" },
  { countryname: "Qatar", flag: "🇶🇦", code: "+974", iso: "QA" },
  { countryname: "Romania", flag: "🇷🇴", code: "+40", iso: "RO" },
  { countryname: "Russia", flag: "🇷🇺", code: "+7", iso: "RU" },
  { countryname: "Rwanda", flag: "🇷🇼", code: "+250", iso: "RW" },
  { countryname: "Saudi Arabia", flag: "🇸🇦", code: "+966", iso: "SA" },
  { countryname: "Senegal", flag: "🇸🇳", code: "+221", iso: "SN" },
  { countryname: "Serbia", flag: "🇷🇸", code: "+381", iso: "RS" },
  { countryname: "Sierra Leone", flag: "🇸🇱", code: "+232", iso: "SL" },
  { countryname: "Singapore", flag: "🇸🇬", code: "+65", iso: "SG" },
  { countryname: "Slovakia", flag: "🇸🇰", code: "+421", iso: "SK" },
  { countryname: "Slovenia", flag: "🇸🇮", code: "+386", iso: "SI" },
  { countryname: "Somalia", flag: "🇸🇴", code: "+252", iso: "SO" },
  { countryname: "South Africa", flag: "🇿🇦", code: "+27", iso: "ZA" },
  { countryname: "South Korea", flag: "🇰🇷", code: "+82", iso: "KR" },
  { countryname: "South Sudan", flag: "🇸🇸", code: "+211", iso: "SS" },
  { countryname: "Spain", flag: "🇪🇸", code: "+34", iso: "ES" },
  { countryname: "Sri Lanka", flag: "🇱🇰", code: "+94", iso: "LK" },
  { countryname: "Sudan", flag: "🇸🇩", code: "+249", iso: "SD" },
  { countryname: "Suriname", flag: "🇸🇷", code: "+597", iso: "SR" },
  { countryname: "Sweden", flag: "🇸🇪", code: "+46", iso: "SE" },
  { countryname: "Switzerland", flag: "🇨🇭", code: "+41", iso: "CH" },
  { countryname: "Syria", flag: "🇸🇾", code: "+963", iso: "SY" },
  { countryname: "Taiwan", flag: "🇹🇼", code: "+886", iso: "TW" },
  { countryname: "Tajikistan", flag: "🇹🇯", code: "+992", iso: "TJ" },
  { countryname: "Tanzania", flag: "🇹🇿", code: "+255", iso: "TZ" },
  { countryname: "Thailand", flag: "🇹🇭", code: "+66", iso: "TH" },
  { countryname: "Togo", flag: "🇹🇬", code: "+228", iso: "TG" },
  { countryname: "Trinidad and Tobago", flag: "🇹🇹", code: "+1868", iso: "TT" },
  { countryname: "Tunisia", flag: "🇹🇳", code: "+216", iso: "TN" },
  { countryname: "Turkey", flag: "🇹🇷", code: "+90", iso: "TR" },
  { countryname: "Turkmenistan", flag: "🇹🇲", code: "+993", iso: "TM" },
  { countryname: "Uganda", flag: "🇺🇬", code: "+256", iso: "UG" },
  { countryname: "Ukraine", flag: "🇺🇦", code: "+380", iso: "UA" },
  { countryname: "United Arab Emirates", flag: "🇦🇪", code: "+971", iso: "AE" },
  { countryname: "United Kingdom", flag: "🇬🇧", code: "+44", iso: "GB" },
  { countryname: "United States", flag: "🇺🇸", code: "+1", iso: "US" },
  { countryname: "Uruguay", flag: "🇺🇾", code: "+598", iso: "UY" },
  { countryname: "Uzbekistan", flag: "🇺🇿", code: "+998", iso: "UZ" },
  { countryname: "Venezuela", flag: "🇻🇪", code: "+58", iso: "VE" },
  { countryname: "Vietnam", flag: "🇻🇳", code: "+84", iso: "VN" },
  { countryname: "Yemen", flag: "🇾🇪", code: "+967", iso: "YE" },
  { countryname: "Zambia", flag: "🇿🇲", code: "+260", iso: "ZM" },
  { countryname: "Zimbabwe", flag: "🇿🇼", code: "+263", iso: "ZW" },
];

export default COUNTRY_PHONES;
